version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db  # Only for local persistence
    ports:
      - "27017:27017" # For local testing
    networks:
      - backend-network # Optional but useful in local dev

  mongodb-driver:
    build:
      context: ../
      dockerfile: build/Dockerfile.dev
    container_name: mongo-driver-backend
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - ../src:/src
      # - ../data:/data
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017
    # command: python3 exercisedbDriver.py  # Example of starting a service, can run from inside container so commented out
    ports:
      - "5000:5000"  # For local testing; AWS Lambda doesn't need this
    networks:
      - backend-network

volumes:
  mongo_data: # Local MongoDB data persistence

networks:
  backend-network: # Local network to connect services
    driver: bridge
